// Code generated by 'guts'. DO NOT EDIT.

// From codersdk/interfacetotype-comments.go
/**
 * Address contains location information.
 */
export type Address = {
    /**
     * Street address
     */
    street: string;
    /**
     * City name
     */
    city: string;
};

// From codersdk/interfacetotype-comments.go
/**
 * Profile combines user and address information.
 * It extends multiple types.
 */
export type Profile = User & Address & {
    /**
     * Bio is the user's biography
     */
    bio: string;
};

// From codersdk/interfacetotype-comments.go
/**
 * User represents a user in the system.
 * This comment should be preserved after conversion to a type alias.
 */
export type User = {
    /**
     * ID is the unique identifier
     */
    id: string;
    /**
     * Name is the user's full name
     */
    name: string;
    /**
     * Email is the user's email address
     */
    email: string;
};
