// Code generated by 'guts'. DO NOT EDIT.

// From array/array.go
export interface StaticArray {
    readonly Numbers: [
        number,
        number,
        number
    ];
    readonly Slice: readonly number[];
    readonly Hash: string;
    readonly SliceHash: string;
}
