// Code generated by 'gots'. DO NOT EDIT.

// From codersdk/genericslice.go
interface Bar {
    Bar: string;
}

// From codersdk/genericslice.go
interface Foo<R extends any> {
    Slice: R[];
    TwoD: R[][];
}
