// Code generated by 'gots'. DO NOT EDIT.

// From maps/map.go
interface Bar<T extends any> {
    SimpleMap: Record<string, string>;
    NumberMap: Record<string, number>;
    GenericMap: Record<string, T>;
}
