//go:build !windows
// +build !windows

package guts_test

import (
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/coder/guts"
	"github.com/coder/guts/config"
)

// loadTypescript wires up a tiny end-to-end pipeline against testdata/array
// so the import mutations have a real serialization path to flow through.
// Each test gets its own Typescript instance because Serialize is one-shot.
func loadTypescript(t *testing.T) *guts.Typescript {
	t.Helper()
	gen, err := guts.NewGolangParser()
	require.NoError(t, err, "new convert")

	dir := filepath.Join(".", "testdata", "array")
	err = gen.IncludeGenerate("./" + dir)
	require.NoErrorf(t, err, "include %q", dir)

	gen.IncludeCustomDeclaration(config.StandardMappings())

	ts, err := gen.ToTypescript()
	require.NoError(t, err, "to typescript")
	return ts
}

// importBlock returns just the prefix before the first declaration, which is
// where Serialize emits the merged imports.
func importBlock(t *testing.T, output string) string {
	t.Helper()
	require.True(t, strings.HasPrefix(output, "// Code generated by 'guts'. DO NOT EDIT."),
		"output must start with the generated header, got %q", output)
	end := strings.Index(output, "interface ")
	if end < 0 {
		end = len(output)
	}
	return output[:end]
}

// TestInjectImport_Merge proves that repeated InjectImport calls for the same
// module collapse into a single statement and that specifiers are sorted by
// name regardless of the order they were appended.
func TestInjectImport_Merge(t *testing.T) {
	t.Parallel()

	ts := loadTypescript(t)
	ts.ApplyMutations(
		config.InjectImport("zod", "z"),
		config.InjectImport("zod", "AnyZod"),
	)
	output, err := ts.Serialize()
	require.NoError(t, err, "serialize")

	require.Contains(t, importBlock(t, output),
		`import { AnyZod, z } from "zod";`,
		"merged value import must include both specifiers in sorted order")
	require.Equal(t, 1, strings.Count(output, `from "zod"`),
		"zod import must be merged")
}

// TestInjectImport_AliasAndType exercises the "Name=Alias" specifier shorthand
// and the type-only declaration form together.
func TestInjectImport_AliasAndType(t *testing.T) {
	t.Parallel()

	ts := loadTypescript(t)
	ts.ApplyMutations(
		config.InjectTypeImport("./types", "Foo", "Bar=Renamed"),
	)
	output, err := ts.Serialize()
	require.NoError(t, err, "serialize")

	require.Contains(t, importBlock(t, output),
		`import type { Bar as Renamed, Foo } from "./types";`,
		"type import must preserve aliasing and sort specifiers by name")
}

// TestInjectImport_MixedTypeAndValueSplit confirms the merge key includes
// IsTypeOnly: mixing InjectImport and InjectTypeImport for the same module
// emits two distinct statements rather than silently flattening the
// type-only intent. Before the merge fix this would produce
// `import { Foo, bar } from "zod";` with Foo demoted to a value import.
func TestInjectImport_MixedTypeAndValueSplit(t *testing.T) {
	t.Parallel()

	ts := loadTypescript(t)
	ts.ApplyMutations(
		config.InjectTypeImport("zod", "Foo"),
		config.InjectImport("zod", "bar"),
	)
	output, err := ts.Serialize()
	require.NoError(t, err, "serialize")

	block := importBlock(t, output)
	require.Contains(t, block, `import { bar } from "zod";`,
		"value import must emit on its own line")
	require.Contains(t, block, `import type { Foo } from "zod";`,
		"type-only intent must not be flattened by the merge")
	require.Equal(t, 2, strings.Count(block, `from "zod"`),
		"mixed-mode imports must emit two separate statements")
	// Value before type-only within the same module.
	valueIdx := strings.Index(block, `import { bar } from "zod";`)
	typeIdx := strings.Index(block, `import type { Foo } from "zod";`)
	require.Less(t, valueIdx, typeIdx,
		"value imports must precede type imports for the same module")
}

// TestInjectImport_SortedAcrossModules pins the cross-module emission order:
// it must be alphabetical by module, not append order. Calling the mutations
// in reverse alphabetical order should still yield the same output.
func TestInjectImport_SortedAcrossModules(t *testing.T) {
	t.Parallel()

	ts := loadTypescript(t)
	ts.ApplyMutations(
		config.InjectImport("zod", "z"),
		config.InjectTypeImport("./types", "Foo"),
	)
	output, err := ts.Serialize()
	require.NoError(t, err, "serialize")

	block := importBlock(t, output)
	typesIdx := strings.Index(block, `from "./types"`)
	zodIdx := strings.Index(block, `from "zod"`)
	require.GreaterOrEqual(t, typesIdx, 0, "./types import must appear")
	require.GreaterOrEqual(t, zodIdx, 0, "zod import must appear")
	require.Less(t, typesIdx, zodIdx,
		"imports must be sorted alphabetically by module")
}

// TestInjectSideEffectImport exercises the bare-import form, deduplication,
// and per-module placement against a clausal import for the same module.
func TestInjectSideEffectImport(t *testing.T) {
	t.Parallel()

	ts := loadTypescript(t)
	ts.ApplyMutations(
		config.InjectImport("zod", "z"),
		config.InjectSideEffectImport("./polyfill"),
		// Second call must dedupe.
		config.InjectSideEffectImport("./polyfill"),
		// Side-effect for a module that also has a clausal import. Side-effect
		// goes before the clausal import for the same module.
		config.InjectSideEffectImport("zod"),
	)
	output, err := ts.Serialize()
	require.NoError(t, err, "serialize")

	block := importBlock(t, output)
	require.Contains(t, block, `import "./polyfill";`,
		"side-effect import must emit with no clause")
	require.Equal(t, 1, strings.Count(block, `import "./polyfill";`),
		"side-effect imports must dedupe per module")

	sideZodIdx := strings.Index(block, `import "zod";`)
	clausalZodIdx := strings.Index(block, `import { z } from "zod";`)
	require.GreaterOrEqual(t, sideZodIdx, 0, "side-effect zod import must appear")
	require.GreaterOrEqual(t, clausalZodIdx, 0, "clausal zod import must appear")
	require.Less(t, sideZodIdx, clausalZodIdx,
		"side-effect import must precede clausal import for the same module")
}
