//go:build !windows
// +build !windows

package guts_test

import (
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/coder/guts"
	"github.com/coder/guts/config"
)

// TestInjectImport runs a tiny end-to-end pipeline (Go package -> Typescript
// AST -> serialize) to confirm that InjectImport and InjectTypeImport are
// emitted before the named declarations, in the order they were appended.
func TestInjectImport(t *testing.T) {
	t.Parallel()

	gen, err := guts.NewGolangParser()
	require.NoError(t, err, "new convert")

	dir := filepath.Join(".", "testdata", "array")
	err = gen.IncludeGenerate("./" + dir)
	require.NoErrorf(t, err, "include %q", dir)

	gen.IncludeCustomDeclaration(config.StandardMappings())

	ts, err := gen.ToTypescript()
	require.NoError(t, err, "to typescript")

	ts.ApplyMutations(
		config.InjectImport("zod", "z"),
		config.InjectTypeImport("./types", "Foo", "Bar=Renamed"),
		// Merging: a second InjectImport for "zod" with a new name should
		// extend the existing import rather than emit a duplicate line.
		config.InjectImport("zod", "AnyZod"),
	)

	output, err := ts.Serialize()
	require.NoError(t, err, "serialize")

	// Header comment is always first.
	require.True(t, strings.HasPrefix(output, "// Code generated by 'guts'. DO NOT EDIT."),
		"output must start with the generated header, got %q", output)

	// Imports must come before any non-comment, non-import declaration.
	importBlockEnd := strings.Index(output, "interface ")
	if importBlockEnd < 0 {
		importBlockEnd = len(output)
	}
	importBlock := output[:importBlockEnd]

	require.Contains(t, importBlock, `import { z, AnyZod } from "zod";`,
		"merged value import must include all specifiers in append order")
	require.Contains(t, importBlock, `import type { Foo, Bar as Renamed } from "./types";`,
		"type import must preserve aliasing")

	// Exactly one import line per module.
	require.Equal(t, 1, strings.Count(output, `from "zod"`), "zod import must be merged")
	require.Equal(t, 1, strings.Count(output, `from "./types"`), "./types import must appear once")
}
