// Code generated by 'guts'. DO NOT EDIT.

// From enums/enums.go
export enum Audience {
    Team = "team",
    Tenant = "tenant",
    World = "world"
}

// From enums/enums.go
export enum EnumInt {
    EnumNumBar = 10,
    EnumNumFoo = 5
}

// From enums/enums.go
export type EnumSliceType = readonly EnumString[];

// From enums/enums.go
export enum EnumString {
    EnumBar = "bar",
    EnumBaz = "baz",
    EnumFoo = "foo",
    EnumQux = "qux"
}
