// Code generated by 'guts'. DO NOT EDIT.

// From enums/enums.go
export enum Audience {
    /**
     * AudienceTeam is the "team" value
     */
    Team = "team",
    Tenant = "tenant",
    World = "world"
}

// From enums/enums.go
export enum EnumInt {
    EnumNumBar = 10,
    /**
     * EnumNumFoo is the number 5
     */
    EnumNumFoo = 5
}

// From enums/enums.go
/**
 * EnumSliceType is a slice of string-based enums
 */
export type EnumSliceType = readonly EnumString[];

// From enums/enums.go
export enum EnumString {
    /**
     * EnumBar is the "bar" value
     */
    EnumBar = "bar",
    EnumBaz = "baz",
    /**
     * EnumFoo is the "foo" value
     * This comment should be preserved
     */
    EnumFoo = "foo",
    EnumQux = "qux"
}
