// Code generated by 'gots'. DO NOT EDIT.

// From codersdk/enums.go
type EnumSliceType = EnumString[];

// From codersdk/enums.go
type EnumString = "bar" | "baz" | "foo" | "qux";

// From codersdk/enums.go
type EnumInt = 10 | 5;
