// Code generated by 'gots'. DO NOT EDIT.

// From codersdk/enums.go
export type EnumInt = 10 | 5;

// From codersdk/enums.go
export type EnumSliceType = EnumString[];

// From codersdk/enums.go
export type EnumString = "bar" | "baz" | "foo" | "qux";
