// Code generated by 'guts'. DO NOT EDIT.

// From notnullmap/notnullmap.go
interface Foo {
    Bar: Record<string, boolean>;
    Nested: GenericFoo<Record<string, number>>;
}

// From notnullmap/notnullmap.go
interface GenericFoo<T extends any> {
    Bar: T;
}
