// Code generated by 'guts'. DO NOT EDIT.

import { z } from "zod";

export type Base = z.infer<typeof BaseSchema>;

export const BaseSchema = z.object({
    id: z.string(),
    created_at: z.string(),
    updated_at: z.string()
});

export type CreateTicketRequest = z.infer<typeof CreateTicketRequestSchema>;

export const CreateTicketRequestSchema = z.object({
    title: z.string(),
    description: z.string().optional(),
    priority: PrioritySchema,
    tags: z.array(z.string()).optional()
});

export type Priority = z.infer<typeof PrioritySchema>;

export const PrioritySchema = z.union([z.literal(2), z.literal(0), z.literal(1)]);

export type Status = z.infer<typeof StatusSchema>;

export const StatusSchema = z.enum(["active", "closed", "pending"]);

export type Ticket = z.infer<typeof TicketSchema>;

export const TicketSchema = BaseSchema.extend({
    title: z.string(),
    description: z.string().optional(),
    status: StatusSchema,
    priority: PrioritySchema,
    assignee_id: z.string().optional(),
    tags: z.array(z.string()),
    metadata: z.record(z.string(), z.string()).nullable(),
    children: z.array(z.lazy((): z.ZodType => TicketSchema))
});

