// Code generated by 'guts'. DO NOT EDIT.

// From zod/types.go
/**
 * Base is embedded by Ticket to test heritage/extend.
 */
export interface Base {
    readonly id: string;
    readonly created_at: string;
    readonly updated_at: string;
}

// From zod/types.go
/**
 * CreateTicketRequest demonstrates a request body type.
 */
export interface CreateTicketRequest {
    readonly title: string;
    readonly description?: string;
    readonly priority: Priority;
    readonly tags?: readonly string[];
}

export const Priorities: Priority[] = [2, 0, 1];

// From zod/types.go
export type Priority = 2 | 0 | 1;

// From zod/types.go
export type Status = "active" | "closed" | "pending";

export const Statuses: Status[] = ["active", "closed", "pending"];

// From zod/types.go
/**
 * Ticket demonstrates a realistic struct with enums, nullable
 * pointers, embedded structs, arrays, and maps.
 */
export interface Ticket extends Base {
    readonly title: string;
    readonly description?: string | null;
    readonly status: Status;
    readonly priority: Priority;
    readonly assignee_id?: string | null;
    readonly tags: readonly string[];
    readonly metadata: Record<string, string> | null;
    readonly children: readonly Ticket[];
}
