// Code generated by 'gots'. DO NOT EDIT.

// From codersdk/interface.go
interface Bar {
    BarField: number;
}

// From codersdk/interface.go
interface Foo extends Bar, GenBar<string> {
}

type Comparable = string | number | boolean;

// From codersdk/interface.go
interface GenBar<T extends Comparable> {
    GenBarField: T;
}
