// Code generated by 'guts'. DO NOT EDIT.

// From maps/map.go
export interface Bar<T extends any> {
    readonly SimpleMap: Record<string, string>;
    readonly NumberMap: Record<string, number>;
    readonly GenericMap: Record<string, T>;
}
