// Code generated by 'guts'. DO NOT EDIT.

// From maps/map.go
export interface Bar<T extends any> {
    readonly SimpleMap: Record<string, string> | null;
    readonly NumberMap: Record<string, number> | null;
    readonly GenericMap: Record<string, T> | null;
}
