// Code generated by 'guts'. DO NOT EDIT.

// From lintignore/lintignore.go
type AnyThing = any;

// From lintignore/lintignore.go
// biome-ignore lint lint/complexity/noUselessTypeConstraint: golang does 'any' for generics, typescript does not like it
interface LintIgnore<T extends any> {
    Foo: T;
}
