// Code generated by 'guts'. DO NOT EDIT.

// From lintignore/lintignore.go
export type AnyThing = any;

// From lintignore/lintignore.go
// biome-ignore lint lint/complexity/noUselessTypeConstraint: golang does 'any' for generics, typescript does not like it
export interface LintIgnore<T extends any> {
    readonly Foo: T;
    // empty interface{} type, falling back to unknown
    readonly AnyFoo: unknown;
}
