// Code generated by 'guts'. DO NOT EDIT.

// From union/union.go
export interface Repeated<T extends string | number> {
    readonly Value: T;
}

// From union/union.go
export interface UnionConstraint<T extends string | number> {
    readonly Value: T;
}
