// Code generated by 'guts'. DO NOT EDIT.

// From codersdk/interfacetotype.go
export type Address = {
    street: string;
    city: string;
    country: string;
};

// From codersdk/interfacetotype.go
export type GenericContainer<T extends any> = {
    value: T;
    count: number;
};

// From codersdk/interfacetotype.go
export type Player = {
    score: number;
};

// From codersdk/interfacetotype.go
export type User = {
    id: number;
    name: string;
    email: string;
    is_active: boolean;
};
