// Code generated by 'gots'. DO NOT EDIT.

// From basicgenerics/basicgenerics.go
export interface Basic<A extends Constraint> {
    readonly Foo: A;
}

// From basicgenerics/basicgenerics.go
export type Constraint = string | boolean;
