// Code generated by 'gots'. DO NOT EDIT.

// From basicgenerics/basicgenerics.go
interface Basic<A extends Constraint> {
    Foo: A;
}

// From basicgenerics/basicgenerics.go
type Constraint = string | boolean;
