// Code generated by 'guts'. DO NOT EDIT.

// From anyreference/anyreference.go
export interface Example {
    readonly Value: Record<string, string>;
}

// From anyreference/anyreference.go
export interface ExampleStruct {
    readonly String: string;
    readonly Int: number;
}

// From anyreference/anyreference.go
export type ExternalString = string;

// From prefix/prefix.go
export type PrefixString = string;

// From prefix/prefix.go
export interface PrefixStruct {
    readonly Field: PrefixString;
}

// From prefix/prefix.go
export type PrefixStructSlice = readonly PrefixStruct[];

// From anyreference/anyreference.go
export type String = string;

// From anyreference/anyreference.go
export interface UsesPrefixPackage {
    readonly Field: PrefixStruct;
    readonly FieldString: PrefixString;
    readonly FieldSlice: PrefixStructSlice;
}
