// Code generated by 'guts'. DO NOT EDIT.

// From codersdk/interface.go
export interface Bar {
    readonly BarField: number;
    readonly ErrorField: string;
}

export type Comparable = string | number | boolean;

// From codersdk/interface.go
export interface Foo extends Bar, GenBar<string> {
}

// From codersdk/interface.go
export interface GenBar<T extends Comparable> {
    readonly GenBarField: T;
}

// From codersdk/interface.go
export type IgnoreMe = any;
