// Package zod serializes a guts TypeScript AST into Zod v4 schema
// declarations. It walks the same intermediate representation that
// the TypeScript serializer uses, so all type mappings, mutations,
// and overrides applied via guts pipelines are reflected in the
// output.
package zod

import (
	"fmt"
	"sort"
	"strings"

	"github.com/coder/guts"
	"github.com/coder/guts/bindings"
)

// Serialize walks all nodes in ts and returns Zod v4 schema code.
// Nodes are emitted in alphabetical order.
func Serialize(ts *guts.Typescript) string {
	nodes := make(map[string]bindings.Node)
	ts.ForEach(func(name string, node bindings.Node) {
		nodes[name] = node
	})

	names := make([]string, 0, len(nodes))
	for name := range nodes {
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("// Code generated by 'guts'. DO NOT EDIT.\n")
	b.WriteString("import { z } from \"zod\";\n\n")

	for _, name := range names {
		s := serializeNode(name, nodes[name])
		if s != "" {
			b.WriteString(s)
			b.WriteString("\n")
		}
	}
	return b.String()
}

// SerializeFilter is like Serialize but only emits nodes for which
// the filter function returns true.
func SerializeFilter(ts *guts.Typescript, filter func(name string) bool) string {
	nodes := make(map[string]bindings.Node)
	ts.ForEach(func(name string, node bindings.Node) {
		if filter(name) {
			nodes[name] = node
		}
	})

	names := make([]string, 0, len(nodes))
	for name := range nodes {
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("// Code generated by 'guts'. DO NOT EDIT.\n")
	b.WriteString("import { z } from \"zod\";\n\n")

	for _, name := range names {
		s := serializeNode(name, nodes[name])
		if s != "" {
			b.WriteString(s)
			b.WriteString("\n")
		}
	}
	return b.String()
}

func serializeNode(name string, node bindings.Node) string {
	switch n := node.(type) {
	case *bindings.Interface:
		return serializeInterface(name, n)
	case *bindings.Alias:
		return serializeAlias(name, n)
	case *bindings.VariableStatement:
		return serializeVariableStatement(name, n)
	default:
		return ""
	}
}

func serializeInterface(name string, iface *bindings.Interface) string {
	schema := schemaName(name)
	var b strings.Builder

	b.WriteString(fmt.Sprintf("export const %s = z.object({\n", schema))
	for _, f := range iface.Fields {
		zodType := exprToZod(f.Type)
		if f.QuestionToken {
			zodType += ".optional()"
		}
		b.WriteString(fmt.Sprintf("  %s: %s,\n", f.Name, zodType))
	}
	b.WriteString("});\n")
	b.WriteString(fmt.Sprintf("export type %s = z.infer<typeof %s>;\n", name, schema))
	return b.String()
}

func serializeAlias(name string, alias *bindings.Alias) string {
	// Enums (union of string literals) become z.enum([...]).
	if union, ok := alias.Type.(*bindings.UnionType); ok {
		if isStringLiteralUnion(union) {
			return serializeStringEnum(name, union)
		}
	}

	schema := schemaName(name)
	zodType := exprToZod(alias.Type)
	var b strings.Builder
	b.WriteString(fmt.Sprintf("export const %s = %s;\n", schema, zodType))
	b.WriteString(fmt.Sprintf("export type %s = z.infer<typeof %s>;\n", name, schema))
	return b.String()
}

func serializeStringEnum(name string, union *bindings.UnionType) string {
	schema := schemaName(name)
	var values []string
	for _, t := range union.Types {
		if lit, ok := t.(*bindings.LiteralType); ok {
			values = append(values, fmt.Sprintf("  %q", lit.Value))
		}
	}
	var b strings.Builder
	b.WriteString(fmt.Sprintf("export const %s = z.enum([\n", schema))
	b.WriteString(strings.Join(values, ",\n"))
	b.WriteString(",\n]);\n")
	b.WriteString(fmt.Sprintf("export type %s = z.infer<typeof %s>;\n", name, schema))
	return b.String()
}

func serializeVariableStatement(name string, vs *bindings.VariableStatement) string {
	// Variable statements are typically enum value lists (const Xs = [...]).
	// Not directly representable in Zod schemas; skip.
	_ = vs
	return ""
}

func exprToZod(expr bindings.ExpressionType) string {
	if expr == nil {
		return "z.unknown()"
	}
	switch e := expr.(type) {
	case *bindings.LiteralKeyword:
		return keywordToZod(e)
	case *bindings.LiteralType:
		return literalToZod(e)
	case *bindings.ReferenceType:
		return referenceToZod(e)
	case *bindings.ArrayType:
		return fmt.Sprintf("z.array(%s)", exprToZod(e.Node))
	case *bindings.UnionType:
		return unionToZod(e)
	case *bindings.Null:
		return "z.null()"
	case *bindings.TypeLiteralNode:
		return objectLiteralToZod(e)
	case *bindings.TypeIntersection:
		return intersectionToZod(e)
	case *bindings.TupleType:
		return tupleToZod(e)
	case *bindings.OperatorNodeType:
		// readonly T[] is still z.array(T) in Zod.
		return exprToZod(e.Type)
	default:
		return "z.unknown()"
	}
}

func keywordToZod(kw *bindings.LiteralKeyword) string {
	switch *kw {
	case bindings.KeywordString:
		return "z.string()"
	case bindings.KeywordNumber:
		return "z.number()"
	case bindings.KeywordBoolean:
		return "z.boolean()"
	case bindings.KeywordAny, bindings.KeywordUnknown:
		return "z.unknown()"
	case bindings.KeywordVoid, bindings.KeywordUndefined:
		return "z.undefined()"
	case bindings.KeywordNever:
		return "z.never()"
	default:
		return "z.unknown()"
	}
}

func literalToZod(lit *bindings.LiteralType) string {
	switch v := lit.Value.(type) {
	case string:
		return fmt.Sprintf("z.literal(%q)", v)
	case bool:
		return fmt.Sprintf("z.literal(%t)", v)
	case int64:
		return fmt.Sprintf("z.literal(%d)", v)
	case float64:
		return fmt.Sprintf("z.literal(%g)", v)
	default:
		return fmt.Sprintf("z.literal(%v)", v)
	}
}

func referenceToZod(ref *bindings.ReferenceType) string {
	name := ref.Name.Ref()
	schema := schemaName(name)

	// Record<K, V> maps to z.record(K, V).
	if name == "Record" && len(ref.Arguments) == 2 {
		return fmt.Sprintf("z.record(%s, %s)",
			exprToZod(ref.Arguments[0]),
			exprToZod(ref.Arguments[1]),
		)
	}

	// Omit, Pick, Partial are TypeScript utility types that don't
	// have direct Zod equivalents. Emit z.unknown() rather than
	// a broken reference.
	switch name {
	case "Omit", "Pick", "Partial", "Required":
		return "z.unknown()"
	}

	_ = schema
	return schema
}

func unionToZod(u *bindings.UnionType) string {
	// Separate null from non-null members.
	nonNull := make([]bindings.ExpressionType, 0, len(u.Types))
	hasNull := false
	for _, t := range u.Types {
		if _, ok := t.(*bindings.Null); ok {
			hasNull = true
		} else {
			nonNull = append(nonNull, t)
		}
	}

	// T | null -> inner.nullable()
	if hasNull && len(nonNull) == 1 {
		return exprToZod(nonNull[0]) + ".nullable()"
	}

	// Single non-null member with no null is just the member.
	if !hasNull && len(nonNull) == 1 {
		return exprToZod(nonNull[0])
	}

	parts := make([]string, 0, len(u.Types))
	for _, t := range u.Types {
		parts = append(parts, exprToZod(t))
	}
	return fmt.Sprintf("z.union([%s])", strings.Join(parts, ", "))
}

func objectLiteralToZod(tl *bindings.TypeLiteralNode) string {
	var b strings.Builder
	b.WriteString("z.object({\n")
	for _, f := range tl.Members {
		zodType := exprToZod(f.Type)
		if f.QuestionToken {
			zodType += ".optional()"
		}
		b.WriteString(fmt.Sprintf("    %s: %s,\n", f.Name, zodType))
	}
	b.WriteString("  })")
	return b.String()
}

func intersectionToZod(inter *bindings.TypeIntersection) string {
	if len(inter.Types) == 0 {
		return "z.unknown()"
	}
	if len(inter.Types) == 1 {
		return exprToZod(inter.Types[0])
	}
	// A & B -> A.merge(B) for objects, but we can't know at
	// serialization time. Use z.intersection for safety.
	parts := make([]string, 0, len(inter.Types))
	for _, t := range inter.Types {
		parts = append(parts, exprToZod(t))
	}
	result := parts[0]
	for _, p := range parts[1:] {
		result = fmt.Sprintf("z.intersection(%s, %s)", result, p)
	}
	return result
}

func tupleToZod(t *bindings.TupleType) string {
	inner := exprToZod(t.Node)
	return fmt.Sprintf("z.array(%s)", inner)
}

func isStringLiteralUnion(u *bindings.UnionType) bool {
	if len(u.Types) == 0 {
		return false
	}
	for _, t := range u.Types {
		lit, ok := t.(*bindings.LiteralType)
		if !ok {
			return false
		}
		if _, ok := lit.Value.(string); !ok {
			return false
		}
	}
	return true
}

func schemaName(typeName string) string {
	return typeName + "Schema"
}
