// Code generated by 'guts'. DO NOT EDIT.

// From tags/tags.go
export interface Tags {
    readonly no_tag: number;
    readonly omit_empty?: number;
    readonly OnlyOmitEmpty?: number;
    readonly "-": number;
    readonly omit_zero?: number;
    readonly OnlyOmitZero?: number;
}
