// Code generated by 'guts'. DO NOT EDIT.

// From codersdk/inheritance.go
export interface Bar {
    readonly BarField: number;
}

// From codersdk/inheritance.go
export interface Buzz {
    readonly bar: string;
}

export type Comparable = string | number | boolean;

// From codersdk/inheritance.go
export interface Foo extends Bar, GenBar<string> {
}

// From codersdk/inheritance.go
export interface FooBuzz {
    readonly foo: Buzz;
    readonly bazz: string;
}

// From codersdk/inheritance.go
export interface GenBar<T extends Comparable> {
    readonly GenBarField: T;
}
