// Code generated by 'guts'. DO NOT EDIT.

// From codersdk/inheritance.go
export interface Bar {
    readonly BarField: number;
}

// From codersdk/inheritance.go
export interface Buzz {
    readonly bar: string;
}

export type Comparable = string | number | boolean;

// From codersdk/inheritance.go
export interface Foo extends Bar, GenBar<string> {
}

// From codersdk/inheritance.go
export interface FooBarPtr extends Bar, GenBar<string> {
}

// From codersdk/inheritance.go
// FooBuzz has a json tag for the embedded
// See: https://go.dev/play/p/-p6QYmY8mtR
export interface FooBuzz {
    readonly foo: Buzz; // Json tag changes the inheritance
    readonly bazz: string;
}

// From codersdk/inheritance.go
export interface GenBar<T extends Comparable> {
    readonly GenBarField: T;
}
