// Code generated by 'guts'. DO NOT EDIT.

// From alias/alias.go
export type Alias = string;

// From alias/alias.go
export type AliasNested = string;

// From alias/alias.go
export type AliasString = string;

// From alias/alias.go
export type AliasStringSlice = readonly string[];

// From alias/alias.go
export interface AliasStruct {
    readonly Key: string;
}

// From alias/alias.go
export interface AliasStructNested {
    readonly Key: string;
}

// From alias/alias.go
export type AliasStructNestedSlice = readonly FooStruct[];

// From alias/alias.go
export type AliasStructSlice = readonly FooStruct[];

// From alias/alias.go
export type Foo = string;

// From alias/alias.go
export interface FooStruct {
    readonly Key: string;
}

// From alias/alias.go
export interface GenericUseRemappedAlias {
    readonly Field: string;
    readonly AsKey: Record<string, string> | null;
    readonly AsVal: Record<string, string> | null;
    readonly AsSlice: readonly string[];
    readonly AsGeneric: string;
}

// From alias/alias.go
export type RemappedAlias = string;

// From alias/alias.go
export interface UseAliasedType<G extends any> {
    readonly Field: string;
    readonly AsKey: Record<string, string> | null;
    readonly AsVal: Record<string, string> | null;
    readonly AsSlice: readonly string[];
    readonly AsGeneric: G;
}
