// Code generated by 'guts'. DO NOT EDIT.

// From alias/alias.go
export type Alias = string;

// From alias/alias.go
export type AliasNested = string;

// From alias/alias.go
export type AliasString = string;

// From alias/alias.go
export type AliasStringSlice = readonly string[];

// From alias/alias.go
export interface AliasStruct {
    readonly Key: string;
}

// From alias/alias.go
export interface AliasStructNested {
    readonly Key: string;
}

// From alias/alias.go
export type AliasStructNestedSlice = readonly FooStruct[];

// From alias/alias.go
export type AliasStructSlice = readonly FooStruct[];

// From alias/alias.go
export type Foo = string;

// From alias/alias.go
export interface FooStruct {
    readonly Key: string;
}
