// Code generated by 'guts'. DO NOT EDIT.

// From alias/alias.go
export type Alias = string;

// From alias/alias.go
export type AliasString = string;

// From alias/alias.go
export type AliasStringSlice = readonly string[];

// From alias/alias.go
export type Foo = string;
