// Code generated by 'guts'. DO NOT EDIT.

// From enumtypes/enumtypes.go
export type Audience = "team" | "tenant" | "world";

export const Audiences: Audience[] = ["team", "tenant", "world"];

// From enumtypes/enumtypes.go
export type EnumAlias = "bool" | "list(string)" | "number" | "string";

export const EnumAliases: EnumAlias[] = ["bool", "list(string)", "number", "string"];

// From enumtypes/enumtypes.go
export type EnumInt = 10 | 5;

export const EnumInts: EnumInt[] = [10, 5];

// From enumtypes/enumtypes.go
export type EnumSliceType = readonly EnumString[];

// From enumtypes/enumtypes.go
export type EnumString = "bar" | "baz" | "foo" | "qux";

export const EnumStrings: EnumString[] = ["bar", "baz", "foo", "qux"];
