// Code generated by 'guts'. DO NOT EDIT.

// From codersdk/enumtypes.go
export type EnumInt = 10 | 5;

export const EnumInts: EnumInt[] = [10, 5];

// From codersdk/enumtypes.go
export type EnumSliceType = readonly EnumString[];

// From codersdk/enumtypes.go
export type EnumString = "bar" | "baz" | "foo" | "qux";

export const EnumStrings: EnumString[] = ["bar", "baz", "foo", "qux"];
