// Code generated by 'guts'. DO NOT EDIT.

// From codersdk/comments.go
// Product represents a product in the system
// This is a multi-line comment
export interface Product {
    // Product identifier
    readonly id: number;
    // Product title
    readonly title: string;
    // Price in cents
    readonly price?: number;
}

// From codersdk/comments.go
// User holds information for a user
export interface User {
    // The name of the user
    readonly name: string;
    // The age of the user
    readonly age: number;
}