// Code generated by 'guts'. DO NOT EDIT.

// From comments/comments.go
/*
  BlockComments are not idiomatic in Go, but can be used
*/
export interface BlockComment {
}

// From comments/comments.go
// CommentedStructure is a struct with a comment.
//
// It actually has 2 comments?!
// TODO: Maybe add a third comment!
export interface CommentedStructure {
    readonly Inline: string; // Field comment
    // Leading comment
    readonly Leading: string;
    readonly Trailing: string;
    // Leading comment
    readonly All: string; // Inline comment
    //  Another leading comment 
    readonly Block: string;
    /* Multi
        Line
        Comment
        */
    readonly MultiLine: string;
}

// From comments/comments.go
// Constant is just a value
export const Constant = "value"; // An inline note


// From comments/comments.go
export interface InheritedCommentedStructure extends CommentedStructure {
}
