// Code generated by 'guts'. DO NOT EDIT.

// From comments/comments.go
/*
  BlockComments are not idiomatic in Go, but can be used
*/
export interface BlockComment {
}

// From comments/comments.go
// CommentedStructure is a struct with a comment.
//
// It actually has 2 comments?!
// TODO: Maybe add a third comment!
export interface CommentedStructure {
    // Field comment
    readonly Inline: string;
    // Leading comment
    readonly Leading: string;
    readonly Trailing: string;
    // Leading comment
    readonly All: string;
    //  Another leading comment 
    readonly Block: string;
}

// From comments/comments.go
export const Constant = "value";
