// Code generated by 'gots'. DO NOT EDIT.

// From codersdk/inheritance.go
export interface Bar {
    readonly BarField: number;
}

export type Comparable = string | number | boolean;

// From codersdk/inheritance.go
export interface Foo extends Bar, GenBar<string> {
}

// From codersdk/inheritance.go
export interface GenBar<T extends Comparable> {
    readonly GenBarField: T;
}
