// Code generated by 'guts'. DO NOT EDIT.

// From prefix/prefix.go
export type Number = number;

// From prefix/prefix.go
export type String = string;

// From prefix/prefix.go
export interface Struct {
    readonly Field: String;
}

// From prefix/prefix.go
export type StructSlice = readonly Struct[];
