// Code generated by 'guts'. DO NOT EDIT.

// From nullable/nullable.go
export interface EmptyFields {
    // empty interface{} type, falling back to unknown
    readonly empty: unknown;
}

// From nullable/nullable.go
export interface NullableFields {
    readonly omitEmpty?: string;
    readonly omitZero?: string;
    readonly nullable: string | null;
    readonly nullableOmitEmpty?: string | null;
    readonly nullableOmitZero?: string | null;
    readonly nullTime: string | null;
    readonly slicePointer: readonly (string)[];
}
