// Code generated by 'gots'. DO NOT EDIT.

// From nullable/nullable.go
export interface EmptyFields {
    // empty interface{} type, falling back to unknown
    readonly empty: unknown;
}

// From nullable/nullable.go
export interface NullableFields {
    readonly omitEmpty?: string;
    readonly nullable: string | null;
    readonly nullableOmitEmpty?: string | null;
}
